nbp-api:
  url: https://api.nbp.pl
  currency:
    uri: /api/exchangerates/rates/A/
  timeout: 5000

server:
  port: 8080
  servlet:
    context-path: /
  front: http://localhost:4200

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true